//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsDB.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }
        public int FilmeID { get; set; }
        public string Resenha { get; set; }
        public int Nota { get; set; }
        public Nullable<int> UsuarioID { get; set; }

        [JsonIgnore]
        public virtual Filmes Filmes { get; set; }
        [JsonIgnore]
        public virtual Usuarios Usuarios { get; set; }
    }
}
