//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBApplicationEntities : DbContext
    {
        public WEBApplicationEntities()
            : base("name=WEBApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atores> Atores { get; set; }
        public virtual DbSet<Filmes> Filmes { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Papeis> Papeis { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Studios> Studios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
